### ISSUE TITLE
Is --standalone option needed for torchrun?

### ISSUE THREAD

**Issue by holgerroth** [Project-MONAI/model-zoo#146]
**Describe the bug**
The `--standalone` option can cause networking issues in certain environments, e.g. cluster. Consider removing it from the bundle docs.

**To Reproduce**
Running in cluster environment can cause network timeout when using the `--standalone` option:
```
2022-09-30 15:33:06,743 - INFO - set logging properties based on config: configs/logging.conf.
[W socket.cpp:601] [c10d] The client socket has failed to connect to [::ffff:0.52.253.213]:59667 (errno: 110 - Connection timed out).
[W socket.cpp:601] [c10d] The client socket has failed to connect to [::ffff:0.52.253.213]:59667 (errno: 110 - Connection timed out).
[W socket.cpp:601] [c10d] The client socket has failed to connect to 0.52.253.213:59667 (errno: 110 - Connection timed out).
[E socket.cpp:657] [c10d] The client socket has failed to connect to any network address of (3472853, 59667).
[W socket.cpp:601] [c10d] The client socket has failed to connect to 0.52.253.213:59667 (errno: 110 - Connection timed out).
[E socket.cpp:657] [c10d] The client socket has failed to connect to any network address of (3472853, 59667).
```

**Expected behavior**
Remove the option from the instructions. 

**Screenshots**

**Environment**
Using monai docker container [1.0.0](https://hub.docker.com/layers/projectmonai/monai/1.0.0/images/sha256-abf0ddabeb49495764c0cae1c601a889efcfcfeb998b6c99e6f9ae2ee820ec7b?context=explore)

**Additional context**
n/a

**Comment by Nic-Ma** [comment]
Hi @holgerroth ,

I think this option is used to simplify the command for `rendezvous backend`:
https://github.com/pytorch/pytorch/blob/master/torch/distributed/run.py#L739
@yiheng-wang-nv could you please help investigate more about it?

Thanks in advance.

**Comment by yiheng-wang-nv** [comment]
Hi @holgerroth , in this case, does remove `--standalone` option solve the issue? and what is the full command that raise the issue?

**Comment by holgerroth** [comment]
Yes, removing the option resolved it on our cluster. The command that caused the issue is the same as in the instructions. Hence, I think we should consider removing this option.
________________________________

**Comment by yiheng-wang-nv** [comment]
Update: I discussed with @holgerroth , and since the `standalone` option is just within the examples section and is also used in pytorch's doc of single-node multi-worker example (https://pytorch.org/docs/stable/elastic/run.html#single-node-multi-worker), here it will not be removed. However, it may introduce some issues if the machine user used is not matched with this option, I will  submit a PR to add some comments within the readme files.
Thanks @holgerroth for posting this question!

**Comment by yiheng-wang-nv** [comment]
Update: I discussed with @holgerroth , since the `standalone` option is just within the `commands example` section for instance, and it is also used in pytorch's doc of single-node multi-worker example (https://pytorch.org/docs/stable/elastic/run.html#single-node-multi-worker), here it will not be removed.

However, it may introduce some issues if the machine that a user used is not matched with this option, I will  submit a PR to add some comments within the readme files to make it more clear.
Thanks @holgerroth for posting this question!
