### ISSUE TITLE
UNesT Code for BTCV

### ISSUE THREAD

**Issue by hanoonaR** [Project-MONAI/model-zoo#165]
Hi,

Recently came across your latest model UNeST, and impressive results on Multi-organ segmentation. But the model zoo does not provide any support for the BTCV organ segmentation task (Table. 5) in the paper. 

Could you please release support for UNesT for the BTCV dataset?

Thank you.

**Comment by Nic-Ma** [comment]
Hi @tangy5 ,

Could you please help share some details about the question?

Thanks in advance.

**Comment by tangy5** [comment]
Hi @hanoonaR Thank you so much for the interests for the UNesT model. About the BTCV release in Model-Zoo, since there are already SwinUNETR model for BTCV, it's the same dataset: https://github.com/Project-MONAI/model-zoo/tree/dev/models/swin_unetr_btcv_segmentation
So we don't have a plan to release UNesT for BTCV in Model-Zoo, the BTCV training is pretty similar to this bundle: https://github.com/Project-MONAI/model-zoo/tree/dev/models/renalStructures_UNEST_segmentation
You could modify the input data and number of segmentation classes, the model used is the same.

In addition, we do have a development code of BTCV experiments, it's from the lab and not for monai bundle, let us know if you'd like this.  

Thanks again!
